FROM node:19.2.0

# WORKDIR is required to set since v15
# Otherwise error npm ERR! Tracker "idealTree" already exists will be raised
WORKDIR /usr/app
EXPOSE 7000

COPY entrypoint.sh /usr/entrypoint.sh
RUN ["chmod", "+x", "/usr/entrypoint.sh"]
ENTRYPOINT ["/usr/entrypoint.sh"]
