version: "3.7"

services:
  nodeserver:
    image: hust/node:0.1.0
    restart: on-failure
    #labels:
    #  traefik.enable: "true"
    #  traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
    #  traefik.http.routers.rocketchat.tls: "true"
    #  traefik.http.routers.rocketchat.entrypoints: https
    #  traefik.http.routers.rocketchat.tls.certresolver: le
    expose:
      - 7000
      - 9229
    ports:
      - "${NODE_HOST_PORT:-7000}:7000"
      - "9229:9229"
    volumes:
      - "${NODE_APP_HOST_DIR}:/usr/app"
