version: "3.7"

services:
  nodeserver:
    image: hust/node:0.2.0
    restart: on-failure
    networks:
      - "antentafm"
    #labels:
    #  traefik.enable: "true"
    #  traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
    #  traefik.http.routers.rocketchat.tls: "true"
    #  traefik.http.routers.rocketchat.entrypoints: https
    #  traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      - NPM_SKIP_START=${NPM_SKIP_START:-}
    expose:
      - 7000
      - 9229
    ports:
      - "7000:7000"
      - "9229:9229"
    volumes:
      - "${NODE_APP_HOST_DIR}:/usr/app"
      - "${RECORDINGS_DIR}:/usr/recordings"

networks:
  antentafm:
