version: "3.7"

volumes:
  icecast_log: { driver: local }
  icecast_cfg: { driver: local }
  icecast_etc: { driver: local }

services:
  icecast:
    image: moul/icecast
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - "antentafm"
    labels:
      traefik.enable: "${TRAEFIK_ENABLED}"
      traefik.http.routers.stream_route.rule: "Host(`stream.${DOMAIN}`)" # Set domain
      traefik.http.routers.stream_route.entrypoints: "web,websecure" # Assign Trafike service
      traefik.http.routers.stream_route.tls: "true"
      traefik.http.routers.stream_route.tls.certresolver: "letsencrypt"
      traefik.http.routers.stream_route.tls.domains[0].main: "stream.${DOMAIN}"
      traefik.http.routers.stream_route.tls.domains[0].sans: "stream.${DOMAIN}"
      traefik.http.routers.stream_route.service: "stream_service" # Assign Trafike service
      traefik.http.services.stream_service.loadbalancer.server.port: "8000" # Port of container used
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - "${ICECAST_CONFIG_FILE}:/etc/icecast2/icecast.xml"
      - icecast_etc:/etc/icecast2
      - icecast_cfg:/config
      - icecast_log:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro

networks:
  antentafm:
