version: "3.7"

volumes:
  icecast_log: { driver: local }
  icecast_cfg: { driver: local }
  icecast_etc: { driver: local }

services:
  icecast:
    image: moul/icecast
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - "antentafm"
    #labels:
    #  traefik.enable: "true"
    #  traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
    #  traefik.http.routers.rocketchat.tls: "true"
    #  traefik.http.routers.rocketchat.entrypoints: https
    #  traefik.http.routers.rocketchat.tls.certresolver: le
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - "${ICECAST_CONFIG_FILE}:/etc/icecast2/icecast.xml"
      - icecast_etc:/etc/icecast2
      - icecast_cfg:/config
      - icecast_log:/var/log/icecast2
      - /etc/localtime:/etc/localtime:ro

networks:
  antentafm:
